setwd("C:\\Users\\twq\\Desktop\\小组作业\\")

dt_02_train <- read.table("1d\\steps_sol_20\\seed_2\\log_test.txt",sep="\t",header = TRUE)
dt_04_train <- read.table("1d\\steps_sol_20\\seed_4\\log_test.txt",sep="\t",header = TRUE)
dt_06_train <- read.table("1d\\steps_sol_20\\seed_6\\log_test.txt",sep="\t",header = TRUE)
dt_08_train <- read.table("1d\\steps_sol_20\\seed_8\\log_test.txt",sep="\t",header = TRUE)
dt_10_train <- read.table("1d\\steps_sol_20\\seed_10\\log_test.txt",sep="\t",header = TRUE)
dt_12_train <- read.table("1d\\steps_sol_20\\seed_12\\log_test.txt",sep="\t",header = TRUE)
dt_14_train <- read.table("1d\\steps_sol_20\\seed_14\\log_test.txt",sep="\t",header = TRUE)
dt_16_train <- read.table("1d\\steps_sol_20\\seed_16\\log_test.txt",sep="\t",header = TRUE)
dt_18_train <- read.table("1d\\steps_sol_20\\seed_18\\log_test.txt",sep="\t",header = TRUE)
dt_20_train <- read.table("1d\\steps_sol_20\\seed_20\\log_test.txt",sep="\t",header = TRUE)


tmp <- data.frame(dim='1D',seed=2,dt_02_train[which(dt_02_train$Epoch==max(dt_02_train$Epoch)),c(5,6)]);cmb_train <- tmp
tmp <- data.frame(dim='1D',seed=4,dt_04_train[which(dt_04_train$Epoch==max(dt_04_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=6,dt_06_train[which(dt_06_train$Epoch==max(dt_06_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=8,dt_08_train[which(dt_08_train$Epoch==max(dt_08_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=10,dt_10_train[which(dt_10_train$Epoch==max(dt_10_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=12,dt_12_train[which(dt_12_train$Epoch==max(dt_12_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=14,dt_14_train[which(dt_14_train$Epoch==max(dt_14_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=16,dt_16_train[which(dt_16_train$Epoch==max(dt_16_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=18,dt_18_train[which(dt_18_train$Epoch==max(dt_18_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='1D',seed=20,dt_20_train[which(dt_20_train$Epoch==max(dt_20_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)



dt_02_train <- read.table("2d\\steps_sol_10\\seed_2\\log_test.txt",sep="\t",header = TRUE)
dt_04_train <- read.table("2d\\steps_sol_10\\seed_4\\log_test.txt",sep="\t",header = TRUE)
dt_06_train <- read.table("2d\\steps_sol_10\\seed_6\\log_test.txt",sep="\t",header = TRUE)
dt_08_train <- read.table("2d\\steps_sol_10\\seed_8\\log_test.txt",sep="\t",header = TRUE)
dt_10_train <- read.table("2d\\steps_sol_10\\seed_10\\log_test.txt",sep="\t",header = TRUE)
dt_12_train <- read.table("2d\\steps_sol_10\\seed_12\\log_test.txt",sep="\t",header = TRUE)
dt_14_train <- read.table("2d\\steps_sol_10\\seed_14\\log_test.txt",sep="\t",header = TRUE)
dt_16_train <- read.table("2d\\steps_sol_10\\seed_16\\log_test.txt",sep="\t",header = TRUE)
dt_18_train <- read.table("2d\\steps_sol_10\\seed_18\\log_test.txt",sep="\t",header = TRUE)
dt_20_train <- read.table("2d\\steps_sol_10\\seed_20\\log_test.txt",sep="\t",header = TRUE)

tmp <- data.frame(dim='2D',seed=2,dt_02_train[which(dt_02_train$Epoch==max(dt_02_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=4,dt_04_train[which(dt_04_train$Epoch==max(dt_04_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=6,dt_06_train[which(dt_06_train$Epoch==max(dt_06_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=8,dt_08_train[which(dt_08_train$Epoch==max(dt_08_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=10,dt_10_train[which(dt_10_train$Epoch==max(dt_10_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=12,dt_12_train[which(dt_12_train$Epoch==max(dt_12_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=14,dt_14_train[which(dt_14_train$Epoch==max(dt_14_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=16,dt_16_train[which(dt_16_train$Epoch==max(dt_16_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=18,dt_18_train[which(dt_18_train$Epoch==max(dt_18_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='2D',seed=20,dt_20_train[which(dt_20_train$Epoch==max(dt_20_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)


dt_02_train <- read.table("3d\\steps_sol_10\\seed_2\\log_test.txt",sep="\t",header = TRUE)
dt_04_train <- read.table("3d\\steps_sol_10\\seed_4\\log_test.txt",sep="\t",header = TRUE)
dt_06_train <- read.table("3d\\steps_sol_10\\seed_6\\log_test.txt",sep="\t",header = TRUE)
dt_08_train <- read.table("3d\\steps_sol_10\\seed_8\\log_test.txt",sep="\t",header = TRUE)
dt_10_train <- read.table("3d\\steps_sol_10\\seed_10\\log_test.txt",sep="\t",header = TRUE)
dt_12_train <- read.table("3d\\steps_sol_10\\seed_12\\log_test.txt",sep="\t",header = TRUE)
dt_14_train <- read.table("3d\\steps_sol_10\\seed_14\\log_test.txt",sep="\t",header = TRUE)
dt_16_train <- read.table("3d\\steps_sol_10\\seed_16\\log_test.txt",sep="\t",header = TRUE)
dt_18_train <- read.table("3d\\steps_sol_10\\seed_18\\log_test.txt",sep="\t",header = TRUE)
dt_20_train <- read.table("3d\\steps_sol_10\\seed_20\\log_test.txt",sep="\t",header = TRUE)

tmp <- data.frame(dim='3D',seed=2,dt_02_train[which(dt_02_train$Epoch==max(dt_02_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=4,dt_04_train[which(dt_04_train$Epoch==max(dt_04_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=6,dt_06_train[which(dt_06_train$Epoch==max(dt_06_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=8,dt_08_train[which(dt_08_train$Epoch==max(dt_08_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=10,dt_10_train[which(dt_10_train$Epoch==max(dt_10_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=12,dt_12_train[which(dt_12_train$Epoch==max(dt_12_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=14,dt_14_train[which(dt_14_train$Epoch==max(dt_14_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=16,dt_16_train[which(dt_16_train$Epoch==max(dt_16_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=18,dt_18_train[which(dt_18_train$Epoch==max(dt_18_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='3D',seed=20,dt_20_train[which(dt_20_train$Epoch==max(dt_20_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)

dt_02_train <- read.table("4d\\steps_sol_10\\seed_2\\log_test.txt",sep="\t",header = TRUE)
dt_04_train <- read.table("4d\\steps_sol_10\\seed_4\\log_test.txt",sep="\t",header = TRUE)
dt_06_train <- read.table("4d\\steps_sol_10\\seed_6\\log_test.txt",sep="\t",header = TRUE)
dt_08_train <- read.table("4d\\steps_sol_10\\seed_8\\log_test.txt",sep="\t",header = TRUE)
dt_10_train <- read.table("4d\\steps_sol_10\\seed_10\\log_test.txt",sep="\t",header = TRUE)
dt_12_train <- read.table("4d\\steps_sol_10\\seed_12\\log_test.txt",sep="\t",header = TRUE)
dt_14_train <- read.table("4d\\steps_sol_10\\seed_14\\log_test.txt",sep="\t",header = TRUE)
dt_16_train <- read.table("4d\\steps_sol_10\\seed_16\\log_test.txt",sep="\t",header = TRUE)
dt_18_train <- read.table("4d\\steps_sol_10\\seed_18\\log_test.txt",sep="\t",header = TRUE)
dt_20_train <- read.table("4d\\steps_sol_10\\seed_20\\log_test.txt",sep="\t",header = TRUE)

tmp <- data.frame(dim='4d',seed=2,dt_02_train[which(dt_02_train$Epoch==max(dt_02_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=4,dt_04_train[which(dt_04_train$Epoch==max(dt_04_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=6,dt_06_train[which(dt_06_train$Epoch==max(dt_06_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=8,dt_08_train[which(dt_08_train$Epoch==max(dt_08_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=10,dt_10_train[which(dt_10_train$Epoch==max(dt_10_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=12,dt_12_train[which(dt_12_train$Epoch==max(dt_12_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=14,dt_14_train[which(dt_14_train$Epoch==max(dt_14_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=16,dt_16_train[which(dt_16_train$Epoch==max(dt_16_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=18,dt_18_train[which(dt_18_train$Epoch==max(dt_18_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
tmp <- data.frame(dim='4d',seed=20,dt_20_train[which(dt_20_train$Epoch==max(dt_20_train$Epoch)),c(5,6)]);cmb_train <- rbind(cmb_train,tmp)
